/**
 * Micro-reward feedback: haptics and celebration tones.
 *
 * One call site (`emitRewardFeedback`) fans out to the platform haptic engine
 * and a synthesized tone, gated by two user preferences (Settings →
 * Accessibility). Feedback is deliberately tiered — a routine check-off gets a
 * light haptic and no sound, while a completed quest or a level-up gets the
 * stronger pattern and the chime — because the design DNA forbids celebrating
 * every checkbox.
 *
 * Every native call is best-effort: feedback must never delay or break the
 * action that triggered it, and it must be a no-op on platforms without the
 * capability (web vibration is opt-in per browser).
 */

import AsyncStorage from '@react-native-async-storage/async-storage';
import { createAudioPlayer, type AudioPlayer } from 'expo-audio';
import * as Haptics from 'expo-haptics';
import { useEffect, useState } from 'react';
import { Platform } from 'react-native';
import { createPreferencePrecedenceGuard } from '@/lib/preferencePrecedence';
import milestoneTone from '../assets/sounds/reward-level.wav';
import questTone from '../assets/sounds/reward-quest.wav';

/**
 * `light` — a single action landed (check-off, log).
 * `success` — a daily quest completed.
 * `milestone` — level-up, badge unlock, streak milestone, complete day.
 */
export type RewardFeedbackTier = 'light' | 'success' | 'milestone';

export type RewardFeedbackPreferences = {
  haptics: boolean;
  sound: boolean;
};

const STORAGE_KEY = 'superhabits.rewardFeedback';
const DEFAULT_PREFERENCES: RewardFeedbackPreferences = { haptics: true, sound: true };

// Assets are generated by scripts/generate-reward-sounds.mjs and committed, so
// playback needs no network and no licensing surface.
const TONE_SOURCES: Partial<Record<RewardFeedbackTier, number | string>> = {
  success: questTone,
  milestone: milestoneTone,
};

let preferences: RewardFeedbackPreferences = { ...DEFAULT_PREFERENCES };
let hydrated = false;
const listeners = new Set<() => void>();
const players = new Map<RewardFeedbackTier, AudioPlayer>();

/** AsyncStorage hydration must never overwrite a newer explicit choice (F-05). */
const preferencePrecedence = createPreferencePrecedenceGuard();

function notifyListeners(): void {
  for (const listener of listeners) {
    listener();
  }
}

function isTier(value: unknown): value is RewardFeedbackTier {
  return value === 'light' || value === 'success' || value === 'milestone';
}

/** Load the persisted preferences once; an explicit choice always wins. */
export function hydrateRewardFeedbackPreferences(): void {
  if (hydrated) return;
  hydrated = true;
  AsyncStorage.getItem(STORAGE_KEY)
    .then((stored) => {
      if (!preferencePrecedence.shouldApplyPersisted() || !stored) return;
      const parsed: unknown = JSON.parse(stored);
      if (typeof parsed !== 'object' || parsed === null) return;
      const record = parsed as Partial<Record<keyof RewardFeedbackPreferences, unknown>>;
      preferences = {
        haptics: typeof record.haptics === 'boolean' ? record.haptics : preferences.haptics,
        sound: typeof record.sound === 'boolean' ? record.sound : preferences.sound,
      };
      notifyListeners();
    })
    .catch(() => {
      // Storage unavailable (private mode): keep the defaults.
    });
}

export function getRewardFeedbackPreferences(): RewardFeedbackPreferences {
  return { ...preferences };
}

/** Persist and apply a preference change (Settings → Accessibility). */
export function setRewardFeedbackPreferences(patch: Partial<RewardFeedbackPreferences>): void {
  preferencePrecedence.markChoiceMade();
  preferences = { ...preferences, ...patch };
  notifyListeners();
  AsyncStorage.setItem(STORAGE_KEY, JSON.stringify(preferences)).catch(() => {
    // The preference still applies for this session even if persistence fails.
  });
}

export function useRewardFeedbackPreferences(): RewardFeedbackPreferences {
  const [observed, setObserved] = useState<RewardFeedbackPreferences>(() => ({
    ...preferences,
  }));

  useEffect(() => {
    hydrateRewardFeedbackPreferences();
    function listener() {
      setObserved({ ...preferences });
    }
    listeners.add(listener);
    return () => {
      listeners.delete(listener);
    };
  }, []);

  return observed;
}

/** True when haptic feedback is available at all on this platform. */
export function isHapticFeedbackSupported(): boolean {
  if (Platform.OS === 'web') {
    return typeof navigator !== 'undefined' && typeof navigator.vibrate === 'function';
  }
  return Platform.OS === 'ios' || Platform.OS === 'android';
}

function triggerHaptic(tier: RewardFeedbackTier): void {
  if (Platform.OS === 'web') {
    // Browsers that implement the Vibration API treat this as a best-effort
    // hint; iOS Safari ignores it entirely and nothing else changes.
    try {
      navigator.vibrate?.(tier === 'light' ? 10 : [12, 40, 18]);
    } catch {
      // Vibration can throw when the document is not visible.
    }
    return;
  }

  const request =
    tier === 'light'
      ? Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light)
      : tier === 'success'
        ? Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success)
        : Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Heavy);
  void request.catch(() => {
    // A device without a haptic engine must not surface an error.
  });
}

/** Lazily create (and reuse) the player for a tone; a failed create degrades to silence. */
function playerFor(tier: RewardFeedbackTier): AudioPlayer | null {
  const source = TONE_SOURCES[tier];
  if (source === undefined) return null;
  const existing = players.get(tier);
  if (existing) return existing;
  try {
    const player = createAudioPlayer(source);
    player.volume = 0.7;
    players.set(tier, player);
    return player;
  } catch {
    return null;
  }
}

function playTone(tier: RewardFeedbackTier): void {
  const player = playerFor(tier);
  if (!player) return;
  try {
    // Rewind first so a rapid second reward restarts the clip instead of
    // being swallowed while the previous one is still playing.
    void player.seekTo(0).catch(() => undefined);
    player.play();
  } catch {
    // Audio focus loss or a platform without playback support.
  }
}

/**
 * Emit the feedback for a reward tier. Silent for `light` sound by design:
 * a chime on every check-off is noise, not reinforcement.
 */
export function emitRewardFeedback(tier: RewardFeedbackTier): void {
  if (!isTier(tier)) return;
  if (preferences.haptics) triggerHaptic(tier);
  if (preferences.sound && tier !== 'light') playTone(tier);
}
