/**
 * Failure digest (`add-user-simulation-platform` task 4.3).
 *
 * Generates a short Markdown document, designed to be pasted verbatim into a
 * defect issue: persona, scenario, failing step, seed, expected vs actual,
 * state summary and artifact links. One digest per failed run, written to
 * `simulation-output/<runId>/digest.md` and referenced from the run report
 * (`report.failure.digestPath`).
 *
 * Pure string building (no fs) — the write path lives in `observe/artifacts.ts`.
 */

import type { RunReport } from './report';

export interface DigestContext {
  /** Free-text state summary captured at failure (e.g. row counts). */
  stateSummary?: string;
}

/** Escape a text fragment for use inside an issue-ready section. */
function codeOrText(v: string | undefined): string {
  return v && v.trim() !== '' ? v.trim().replace(/\n/g, ' ') : '*not captured*';
}

/**
 * Build the failure digest Markdown for a run report. Accepts reports that
 * failed OR passed (a digest for a passing run documents the run; callers
 * normally only write it for failures).
 */
export function buildFailureDigest(report: RunReport, ctx: DigestContext = {}): string {
  const lines: string[] = [];
  lines.push('# Failure digest');
  lines.push('');
  lines.push(
    '<!-- generated by `simulation/observe/digest.ts` — fill in the defect title below -->',
  );
  lines.push('');
  lines.push(
    '- **Persona**: ' +
      (report.persona ? `${report.persona.name} (${report.persona.id})` : '*none*'),
  );
  lines.push(
    '- **Scenario**: ' +
      (report.scenario ? `${report.scenario.id} — ${report.scenario.goal}` : '*ad-hoc*'),
  );
  lines.push('- **Lane**: ' + report.lane);
  lines.push(
    '- **Mode**: ' + report.mode + (report.seed !== null ? ` — seed \`${report.seed}\`` : ''),
  );
  lines.push('- **Run id**: ' + report.runId);
  lines.push(
    '- **Environment**: ' +
      `${report.environment.browser} (${report.environment.platform}) @ ${report.environment.baseUrl}`,
  );
  lines.push('- **Outcome**: ' + report.outcome);
  lines.push(
    '- **Classification**: ' +
      (report.triage?.classification ?? 'UNTRIAGED — reproduce and classify before changing code'),
  );
  lines.push('- **Run report**: `' + report.artifacts.report + '`');
  lines.push('');

  if (report.failure) {
    const f = report.failure;
    lines.push('## Failed step');
    lines.push('');
    lines.push(`Step **#${f.stepIndex}** — \`${f.stepKind}\``);
    lines.push('');
    lines.push('- **Action**: `' + codeOrText(f.action) + '`');
    lines.push('');
    lines.push('### Expected vs. actual');
    lines.push('');
    lines.push('- **Expected**: ' + codeOrText(f.expected));
    lines.push('- **Actual**: ' + codeOrText(f.actual));
    lines.push('- **Error**: `' + codeOrText(f.error) + '`');
    lines.push('');
    lines.push('### State summary');
    lines.push('');
    lines.push(codeOrText(ctx.stateSummary ?? f.stateSummary));
    lines.push('');
    lines.push('### Browser/server diagnostics');
    lines.push('');
    lines.push('- **Browser errors**: ' + codeOrText(f.browserErrors?.join(' | ')));
    lines.push('- **Server errors**: ' + codeOrText(f.serverErrors?.join(' | ')));
    lines.push('');
  } else {
    lines.push('## No failure recorded');
    lines.push('');
    lines.push('This digest was produced for a non-failed run (informational).');
    lines.push('');
  }

  lines.push('## Artifacts');
  lines.push('');
  const a = report.artifacts;
  lines.push('- Report: `' + a.report + '`');
  if (a.digest) lines.push('- Digest: `' + a.digest + '`');
  if (a.screenshots.length > 0) {
    lines.push('- Screenshots:');
    for (const s of a.screenshots) lines.push('  - `' + s + '`');
  }
  if (a.video) lines.push('- Video: `' + a.video + '`');
  if (a.trace) lines.push('- Trace: `' + a.trace + '`');
  if (a.consoleLog) lines.push('- Console log: `' + a.consoleLog + '`');
  lines.push('');

  lines.push('## Steps (expanded graph)');
  lines.push('');
  lines.push('| # | kind | status | duration |');
  lines.push('|---|------|--------|----------|');
  for (const s of report.steps) {
    lines.push(`| ${s.index} | \`${s.kind}\` | ${s.status} | ${s.durationMs}ms |`);
  }
  lines.push('');
  lines.push('## Repro notes');
  lines.push('');
  const seedNote =
    report.seed !== null
      ? `Replay exactly with: \`npm run sim:run -- --scenario ${report.scenario?.id ?? '<scenario>'} --mode ${report.mode} --seed ${report.seed}\``
      : 'No deterministic seed available for this lane; replay via the captured trace/state bundle.';
  lines.push(seedNote);
  lines.push(
    report.triage
      ? `Triage rationale: ${codeOrText(report.triage.rationale)}\nEvidence: ${report.triage.evidence.map((entry) => `\`${entry}\``).join(', ')}`
      : 'Do not label this failure flaky solely because a retry passes. Use the six-value triage contract and retain the original evidence.',
  );
  lines.push('');

  return lines.join('\n');
}
