import type { WorkoutModality } from '@/core/db/types';

export type ExerciseCatalogItem = {
  id: string;
  name: string;
  modality: WorkoutModality;
  primaryArea: string;
  secondaryAreas: string[];
  equipment: string;
  unilateral: boolean;
  description?: string;
};

/**
 * Small, repository-authored starter catalog. These stable IDs are application
 * source, not user rows: custom exercises are stored separately and legacy
 * free-text rows never get guessed into this list.
 */
export const BUILT_IN_EXERCISES: readonly ExerciseCatalogItem[] = [
  {
    id: 'builtin_barbell_bench_press',
    name: 'Barbell Bench Press',
    modality: 'weighted_strength',
    primaryArea: 'chest',
    secondaryAreas: ['triceps', 'shoulders'],
    equipment: 'barbell',
    unilateral: false,
  },
  {
    id: 'builtin_dumbbell_bench_press',
    name: 'Dumbbell Bench Press',
    modality: 'weighted_strength',
    primaryArea: 'chest',
    secondaryAreas: ['triceps', 'shoulders'],
    equipment: 'dumbbells',
    unilateral: false,
  },
  {
    id: 'builtin_push_up',
    name: 'Push-up',
    modality: 'bodyweight',
    primaryArea: 'chest',
    secondaryAreas: ['triceps', 'core'],
    equipment: 'bodyweight',
    unilateral: false,
  },
  {
    id: 'builtin_incline_push_up',
    name: 'Incline Push-up',
    modality: 'bodyweight',
    primaryArea: 'chest',
    secondaryAreas: ['triceps', 'core'],
    equipment: 'bodyweight',
    unilateral: false,
  },
  {
    id: 'builtin_barbell_row',
    name: 'Barbell Row',
    modality: 'weighted_strength',
    primaryArea: 'back',
    secondaryAreas: ['biceps', 'core'],
    equipment: 'barbell',
    unilateral: false,
  },
  {
    id: 'builtin_lat_pulldown',
    name: 'Lat Pulldown',
    modality: 'weighted_strength',
    primaryArea: 'back',
    secondaryAreas: ['biceps'],
    equipment: 'cable',
    unilateral: false,
  },
  {
    id: 'builtin_pull_up',
    name: 'Pull-up',
    modality: 'bodyweight',
    primaryArea: 'back',
    secondaryAreas: ['biceps', 'core'],
    equipment: 'pull-up bar',
    unilateral: false,
  },
  {
    id: 'builtin_assisted_pull_up',
    name: 'Assisted Pull-up',
    modality: 'weighted_strength',
    primaryArea: 'back',
    secondaryAreas: ['biceps'],
    equipment: 'machine',
    unilateral: false,
  },
  {
    id: 'builtin_single_arm_dumbbell_row',
    name: 'Single-arm Dumbbell Row',
    modality: 'weighted_strength',
    primaryArea: 'back',
    secondaryAreas: ['biceps', 'core'],
    equipment: 'dumbbells',
    unilateral: true,
  },
  {
    id: 'builtin_overhead_press',
    name: 'Overhead Press',
    modality: 'weighted_strength',
    primaryArea: 'shoulders',
    secondaryAreas: ['triceps', 'core'],
    equipment: 'barbell',
    unilateral: false,
  },
  {
    id: 'builtin_dumbbell_shoulder_press',
    name: 'Dumbbell Shoulder Press',
    modality: 'weighted_strength',
    primaryArea: 'shoulders',
    secondaryAreas: ['triceps'],
    equipment: 'dumbbells',
    unilateral: false,
  },
  {
    id: 'builtin_lateral_raise',
    name: 'Lateral Raise',
    modality: 'weighted_strength',
    primaryArea: 'shoulders',
    secondaryAreas: [],
    equipment: 'dumbbells',
    unilateral: false,
  },
  {
    id: 'builtin_face_pull',
    name: 'Face Pull',
    modality: 'weighted_strength',
    primaryArea: 'shoulders',
    secondaryAreas: ['back'],
    equipment: 'cable',
    unilateral: false,
  },
  {
    id: 'builtin_barbell_curl',
    name: 'Barbell Curl',
    modality: 'weighted_strength',
    primaryArea: 'biceps',
    secondaryAreas: [],
    equipment: 'barbell',
    unilateral: false,
  },
  {
    id: 'builtin_dumbbell_curl',
    name: 'Dumbbell Curl',
    modality: 'weighted_strength',
    primaryArea: 'biceps',
    secondaryAreas: [],
    equipment: 'dumbbells',
    unilateral: false,
  },
  {
    id: 'builtin_hammer_curl',
    name: 'Hammer Curl',
    modality: 'weighted_strength',
    primaryArea: 'biceps',
    secondaryAreas: ['forearms'],
    equipment: 'dumbbells',
    unilateral: false,
  },
  {
    id: 'builtin_triceps_pushdown',
    name: 'Triceps Pushdown',
    modality: 'weighted_strength',
    primaryArea: 'triceps',
    secondaryAreas: [],
    equipment: 'cable',
    unilateral: false,
  },
  {
    id: 'builtin_dips',
    name: 'Dips',
    modality: 'bodyweight',
    primaryArea: 'triceps',
    secondaryAreas: ['chest', 'shoulders'],
    equipment: 'dip bars',
    unilateral: false,
  },
  {
    id: 'builtin_back_squat',
    name: 'Back Squat',
    modality: 'weighted_strength',
    primaryArea: 'quads',
    secondaryAreas: ['glutes', 'core'],
    equipment: 'barbell',
    unilateral: false,
  },
  {
    id: 'builtin_front_squat',
    name: 'Front Squat',
    modality: 'weighted_strength',
    primaryArea: 'quads',
    secondaryAreas: ['glutes', 'core'],
    equipment: 'barbell',
    unilateral: false,
  },
  {
    id: 'builtin_leg_press',
    name: 'Leg Press',
    modality: 'weighted_strength',
    primaryArea: 'quads',
    secondaryAreas: ['glutes'],
    equipment: 'machine',
    unilateral: false,
  },
  {
    id: 'builtin_walking_lunge',
    name: 'Walking Lunge',
    modality: 'weighted_strength',
    primaryArea: 'quads',
    secondaryAreas: ['glutes', 'hamstrings'],
    equipment: 'dumbbells',
    unilateral: true,
  },
  {
    id: 'builtin_bulgarian_split_squat',
    name: 'Bulgarian Split Squat',
    modality: 'weighted_strength',
    primaryArea: 'quads',
    secondaryAreas: ['glutes', 'hamstrings'],
    equipment: 'dumbbells',
    unilateral: true,
  },
  {
    id: 'builtin_romanian_deadlift',
    name: 'Romanian Deadlift',
    modality: 'weighted_strength',
    primaryArea: 'hamstrings',
    secondaryAreas: ['glutes', 'back'],
    equipment: 'barbell',
    unilateral: false,
  },
  {
    id: 'builtin_lying_leg_curl',
    name: 'Lying Leg Curl',
    modality: 'weighted_strength',
    primaryArea: 'hamstrings',
    secondaryAreas: [],
    equipment: 'machine',
    unilateral: false,
  },
  {
    id: 'builtin_hip_thrust',
    name: 'Hip Thrust',
    modality: 'weighted_strength',
    primaryArea: 'glutes',
    secondaryAreas: ['hamstrings'],
    equipment: 'barbell',
    unilateral: false,
  },
  {
    id: 'builtin_glute_bridge',
    name: 'Glute Bridge',
    modality: 'bodyweight',
    primaryArea: 'glutes',
    secondaryAreas: ['hamstrings'],
    equipment: 'bodyweight',
    unilateral: false,
  },
  {
    id: 'builtin_calf_raise',
    name: 'Standing Calf Raise',
    modality: 'weighted_strength',
    primaryArea: 'calves',
    secondaryAreas: [],
    equipment: 'machine',
    unilateral: false,
  },
  {
    id: 'builtin_single_leg_calf_raise',
    name: 'Single-leg Calf Raise',
    modality: 'bodyweight',
    primaryArea: 'calves',
    secondaryAreas: [],
    equipment: 'bodyweight',
    unilateral: true,
  },
  {
    id: 'builtin_plank',
    name: 'Plank',
    modality: 'timed',
    primaryArea: 'core',
    secondaryAreas: ['shoulders'],
    equipment: 'bodyweight',
    unilateral: false,
  },
  {
    id: 'builtin_side_plank',
    name: 'Side Plank',
    modality: 'timed',
    primaryArea: 'core',
    secondaryAreas: ['shoulders'],
    equipment: 'bodyweight',
    unilateral: true,
  },
  {
    id: 'builtin_dead_bug',
    name: 'Dead Bug',
    modality: 'bodyweight',
    primaryArea: 'core',
    secondaryAreas: [],
    equipment: 'bodyweight',
    unilateral: true,
  },
  {
    id: 'builtin_hanging_knee_raise',
    name: 'Hanging Knee Raise',
    modality: 'bodyweight',
    primaryArea: 'core',
    secondaryAreas: ['hip flexors'],
    equipment: 'pull-up bar',
    unilateral: false,
  },
  {
    id: 'builtin_burpee',
    name: 'Burpee',
    modality: 'bodyweight',
    primaryArea: 'full-body',
    secondaryAreas: ['chest', 'quads', 'core'],
    equipment: 'bodyweight',
    unilateral: false,
  },
  {
    id: 'builtin_mountain_climber',
    name: 'Mountain Climber',
    modality: 'timed',
    primaryArea: 'full-body',
    secondaryAreas: ['core', 'shoulders'],
    equipment: 'bodyweight',
    unilateral: true,
  },
  {
    id: 'builtin_treadmill_walk',
    name: 'Treadmill Walk',
    modality: 'cardio',
    primaryArea: 'cardio',
    secondaryAreas: ['quads', 'calves'],
    equipment: 'treadmill',
    unilateral: false,
  },
  {
    id: 'builtin_treadmill_run',
    name: 'Treadmill Run',
    modality: 'cardio',
    primaryArea: 'cardio',
    secondaryAreas: ['quads', 'calves'],
    equipment: 'treadmill',
    unilateral: false,
  },
  {
    id: 'builtin_stationary_bike',
    name: 'Stationary Bike',
    modality: 'cardio',
    primaryArea: 'cardio',
    secondaryAreas: ['quads', 'calves'],
    equipment: 'bike',
    unilateral: false,
  },
  {
    id: 'builtin_rowing_machine',
    name: 'Rowing Machine',
    modality: 'cardio',
    primaryArea: 'cardio',
    secondaryAreas: ['back', 'quads'],
    equipment: 'rower',
    unilateral: false,
  },
  {
    id: 'builtin_elliptical',
    name: 'Elliptical',
    modality: 'cardio',
    primaryArea: 'cardio',
    secondaryAreas: ['quads', 'glutes'],
    equipment: 'elliptical',
    unilateral: false,
  },
  {
    id: 'builtin_jump_rope',
    name: 'Jump Rope',
    modality: 'cardio',
    primaryArea: 'cardio',
    secondaryAreas: ['calves'],
    equipment: 'jump rope',
    unilateral: false,
  },
  {
    id: 'builtin_kettlebell_swing',
    name: 'Kettlebell Swing',
    modality: 'weighted_strength',
    primaryArea: 'full-body',
    secondaryAreas: ['glutes', 'hamstrings', 'core'],
    equipment: 'kettlebell',
    unilateral: false,
  },
  {
    id: 'builtin_farmer_carry',
    name: 'Farmer Carry',
    modality: 'timed',
    primaryArea: 'full-body',
    secondaryAreas: ['forearms', 'core'],
    equipment: 'dumbbells',
    unilateral: false,
  },
] as const;

const BUILT_IN_BY_ID = new Map(BUILT_IN_EXERCISES.map((exercise) => [exercise.id, exercise]));

export function getBuiltInExercise(id: string | null | undefined): ExerciseCatalogItem | null {
  return id ? (BUILT_IN_BY_ID.get(id) ?? null) : null;
}

export function isBuiltInExerciseId(id: string | null | undefined): boolean {
  return typeof id === 'string' && BUILT_IN_BY_ID.has(id);
}

export function listBuiltInExerciseFilters(): { areas: string[]; equipment: string[] } {
  return {
    areas: [...new Set(BUILT_IN_EXERCISES.map((exercise) => exercise.primaryArea))].sort(),
    equipment: [...new Set(BUILT_IN_EXERCISES.map((exercise) => exercise.equipment))].sort(),
  };
}
